image: openjdk:8-jdk

stages:
  - linter
  - test
  - build
  - tag

variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.0"
  ANDROID_SDK_TOOLS:   "6609375" # from https://developer.android.com/studio/#command-tools
  CMAKE:               "3.10.2.4988404"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -d cmdline-tools android-sdk.zip

  - echo yes | cmdline-tools/tools/bin/sdkmanager  "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo yes | cmdline-tools/tools/bin/sdkmanager  "platform-tools" >/dev/null
  - echo yes | cmdline-tools/tools/bin/sdkmanager  "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - echo yes | cmdline-tools/tools/bin/sdkmanager  "ndk-bundle" >/dev/null
  - echo yes | cmdline-tools/tools/bin/sdkmanager  "cmake;${CMAKE}" >/dev/null

  - export ANDROID_SDK_ROOT=$PWD/cmdline-tools/
  - export CMAKE_HOME=$PWD/cmdline-tools/cmake/${CMAKE}/bin/
  - export PATH=$PATH:$PWD/cmdline-tools/platform-tools/:$CMAKE_HOME
  - mkdir "$ANDROID_SDK_ROOT/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_SDK_ROOT/licenses/android-sdk-license"

  - chmod +x ./gradlew
  - set +o pipefail
  - yes | cmdline-tools/tools/bin/sdkmanager --licenses
  - set -o pipefail

lint:
  stage: linter
  script:
    - ./gradlew -Pci --console=plain lintDebug -PbuildDir=lint

unitTest:
  stage: test
  script:
    - ./gradlew -Pci --console=plain testDebug

#instrumentationTest:
#  stage: test
#  script:
#    - echo y | cmdline-tools/tools/bin/sdkmanager  "emulator" >/dev/null
#    - echo y | cmdline-tools/tools/bin/sdkmanager "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86"
#    - echo y | cmdline-tools/tools/bin/avdmanager create avd -f -n testAVD -k "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86"
#    - cmdline-tools/emulator/emulator -avd testAVD -no-audio -no-window &
#    - ./gradlew connectedAndroidTest

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - mobile-ui/build/outputs/

semantic_release:
  stage: tag
  image: node:10.19
  variables:
    GITLAB_TOKEN: $ACCESS_TOKEN
  before_script:
    - npm install -g semantic-release @semantic-release/git @semantic-release/gitlab
    - npm install @semantic-release/changelog -D
    - cat $SEM_RELEASE_OPTIONS > .releaserc.yml
  script:
    - semantic-release
  only:
    - master
    - next
    - beta
