object Versions {
    const val androidBuildToolsVersion = "30.0.0"
    const val androidMinSdkVersion = 21
    const val androidTargetSdkVersion = 30
    const val androidCompileSdkVersion = 30
    const val kotlinVersion = "1.4.10"

    const val rxKotlinVersion = "2.4.0"
    const val javaxAnnotationVersion = "1.0"
    const val javaxInjectVersion = "1"
    const val androidAnnotationsVersion = "1.1.0"
    const val daggerVersion = "2.29.1"
    const val gsonVersion = "2.8.6"
    const val okHttpVersion = "4.9.0"
    const val retrofitVersion = "2.9.0"
    const val archTestingVersion = "2.1.0"
    const val roomVersion = "2.2.5"
    const val androidLifecycleVersion = "2.2.0"
    const val glideVersion = "4.11.0"
    const val timberVersion = "4.7.1"
    const val androidCoreVersion = "1.3.1"
    const val androidCompatVersion = "1.2.0"
    const val rxAndroidVersion = "2.1.1"
    const val hiltVersion = "2.29-alpha"
    const val hiltViewModelVersion = "1.0.0-alpha02"

    const val jUnitVersion = "4.13"
    const val assertJVersion = "3.17.2"
    const val mockitoKotlinVersion = "2.2.0"
    const val robolectricVersion = "4.4"
    const val androidTestRunnerVersion = "1.1.0"
    const val androidTestRulesVersion = "1.1.0"
    const val espressoVersion = "3.3.0"
}

object Dependencies {
    const val javaxAnnotation = "javax.annotation:jsr250-api:${Versions.javaxAnnotationVersion}"
    const val javaxInject = "javax.inject:javax.inject:${Versions.javaxInjectVersion}"
    const val rxKotlin = "io.reactivex.rxjava2:rxkotlin:${Versions.rxKotlinVersion}"
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlinVersion}"

    const val gson = "com.google.code.gson:gson:${Versions.gsonVersion}"
    const val okHttp = "com.squareup.okhttp3:okhttp:${Versions.okHttpVersion}"
    const val okHttpLogger = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttpVersion}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofitVersion}"
    const val retrofitConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofitVersion}"
    const val retrofitAdapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofitVersion}"
    const val daggerCompiler= "com.google.dagger:dagger-compiler:${Versions.daggerVersion}"
    const val dagger= "com.google.dagger:dagger:${Versions.daggerVersion}"
    const val androidAnnotations= "androidx.annotation:annotation:${Versions.androidAnnotationsVersion}"
    const val roomRuntime= "androidx.room:room-runtime:${Versions.roomVersion}"
    const val roomCompiler= "androidx.room:room-compiler:${Versions.roomVersion}"
    const val roomRxJava= "androidx.room:room-rxjava2:${Versions.roomVersion}"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.androidLifecycleVersion}"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.androidLifecycleVersion}"
    const val lifecycleLiveData = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.androidLifecycleVersion}"
    const val lifecycleCompiler = "androidx.lifecycle:lifecycle-compiler:${Versions.androidLifecycleVersion}"
    const val daggerAndroid = "com.google.dagger:dagger-android:${Versions.daggerVersion}"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroidVersion}"
    const val androidCore = "androidx.core:core-ktx:${Versions.androidCoreVersion}"
    const val androidCompat = "androidx.appcompat:appcompat:${Versions.androidCompatVersion}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timberVersion}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glideVersion}"
    const val daggerSupportAndroid = "com.google.dagger:dagger-android-support:${Versions.daggerVersion}"
    const val daggerAndroidProcessor = "com.google.dagger:dagger-android-processor:${Versions.daggerVersion}"


    const val junit = "junit:junit:${Versions.jUnitVersion}"
    const val mockito = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Versions.mockitoKotlinVersion}"
    const val assertj = "org.assertj:assertj-core:${Versions.assertJVersion}"
    const val kotlinJUnit = "org.jetbrains.kotlin:kotlin-test-junit:${Versions.kotlinVersion}"
    const val androidTestRunner = "androidx.test:runner:${Versions.androidTestRunnerVersion}"
    const val androidTestRules = "androidx.test:rules:${Versions.androidTestRulesVersion}"
    const val androidTestCore = "androidx.test:core:${Versions.androidTestRulesVersion}"
    const val archTesting = "androidx.arch.core:core-testing:${Versions.archTestingVersion}"
    const val roomTesting = "androidx.room:room-testing:${Versions.roomVersion}"
    const val robolectric = "org.robolectric:robolectric:${Versions.robolectricVersion}"
    const val espressoCore = "androidx.test.espresso:espresso-core:${Versions.espressoVersion}"
}